# Generated by the vetiver package; edit with care

FROM public.ecr.aws/lambda/provided
RUN yum -y install wget tar
RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
  wget https://cdn.rstudio.com/r/centos-7/pkgs/R-4.2.1-1-1.x86_64.rpm && \
  yum -y install R-4.2.1-1-1.x86_64.rpm && \
  rm R-4.2.1-1-1.x86_64.rpm
ENV PATH="${PATH}:/opt/R/4.2.1/bin/"
RUN echo 'options(repos = c(CRAN = "https://cran.rstudio.com/"))' >> /opt/R/4.2.1/lib/R/etc/Rprofile.site
ENV RENV_CONFIG_REPOS_OVERRIDE https://packagemanager.rstudio.com/all/__linux__/centos7/latest

RUN yum update -y && yum install -y \
  libcurl-devel \
  libicu-devel \
  libsodium-devel \
  make \
  openssl-devel && \
  yum clean all

COPY vetiver_renv.lock renv.lock
RUN Rscript -e "install.packages('renv')"
RUN Rscript -e "renv::restore()"
COPY runtime.R /opt/ml/runtime.R
RUN printf '#!/bin/sh\nRscript /opt/ml/runtime.R' > /var/runtime/bootstrap \
        && chmod +x /var/runtime/bootstrap
CMD ["predict"]
