# Generated by the vetiver package; edit with care

library(pins)
library(lambdr)
library(vetiver)

# Required to stop pins from trying to write to the home directory
# See https://github.com/rstudio/pins-r/issues/611
Sys.setenv(R_USER_CACHE_DIR = tempfile())
Sys.setenv(R_USER_DATA_DIR = tempfile())

b <- board_s3(bucket = "CENSORED")
v <- vetiver_pin_read(b, "simpsons", version = "20220813T224517Z-b6960")

vetiver_predict <- function(...) {
    predict(v, as.data.frame(...))
}
start_lambda()
